### PR TITLE
Bugfix/jdw.returning.aggrid.states

### LINKED ISSUE #13: Incomplete return from AgGrid
**Describe the bug**
The AgGrid return value contains several elements (rowData, selectedData, selectedRows, selectedItems) that are not passed to the Python side.

**Minimum working example**
Please provide the minimum working example that shows the bug,
```python
import pandas as pd
import streamlit as st
import streamlit_aggrid_redux as sgr

data = pd.DataFrame({
        "a": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "a+a": [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
        "a*a": [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
    })

gob = sgr.GridOptionsBuilder.from_data(data)
gob.add_grid_selection(use_checkbox=True, selection_mode="multiple")
tmp = sgr.ag_grid(
    data,
    gob.build(),
    return_mode="filter sort"
)
st.write("output is :")
st.write(tmp)
```

will yield
```
GridReturn(data= a a+a a*a 0 1 2 1 1 2 4 4 2 3 6 9 3 4 8 16 4 5 10 25 5 6 12 36 6 7 14 49 7 8 16 64 8 9 18 81 9 10 20 100, selected_rows=None, columns_state=None)
```

**Expected behavior**
The GridReturn object should yield everything from the [AgGrid.tsx return](https://github.com/jwood983/streamlit-aggrid-redux/blob/main/streamlit_aggrid_redux/frontend/src/AgGrid.tsx#L317):
```typescript
let returnValue = {
        rowData: returnData,
        selectedData: selected,
        selectedRows: this.api.getSelectedRows(),
        selectedItems: this.api.getSelectedNodes().map((n: { rowIndex: any; id: any; data: any }, i: any) => ({
            _selectedRowNodeInfo: { nodeRowIndex: n.rowIndex, nodeId: n.id },
            ...n.data,
        }))
    }
```

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser all
 - Version N/a

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by jwood983**
# Proposed change description
_Describe the proposed changes. If connected to an Issue, please include the link to the relevant Issue._
Fixes #13 by forcing insertion of `selectionChanged` to set of AgGrid listeners so that when a user checks a box, it will return the line back to them in the `selected_rows` and `selected_items` variables.

# Test plan
_Provide positive evidence of tests that support the change. Simply stating "Passed tests" or other some such is cause for immediate closure._
Test is coming in next PR to ensure it works.

### CODE REVIEW

File: streamlit_aggrid_redux/frontend/src/AgGrid.tsx [hunk 1]
```diff
@@ -116,17 +116,6 @@ function QuickSearch(props: any) {
     return <></>
 }
 
-function ManualUpdateButton(props: any) {
-    if (props.manualUpdate) {
```
Comment (jwood983) [inline streamlit_aggrid_redux/frontend/src/AgGrid.tsx:120]: I don't know when adding a manual button to reload was sensible, so I removed it

File: streamlit_aggrid_redux/frontend/src/AgGrid.tsx [hunk 2]
```diff
@@ -184,12 +175,21 @@ class AgGrid<S = {}> extends React.Component<ComponentProps, S> {
...
+        this.isGridAutoHeightOn = this.props.args.grid_options?.domLayout === "autoHeight"
+
+        if (("clearCheckboxOnReload" in this.props.args.grid_options)) {
+            this.clearCheckboxOnReload = this.props.args.grid_options["clearCheckboxOnReload"];
+            delete this.props.args.grid_options["clearCheckboxOnReload"];
+        }
+        if (("preSelectAllRows" in this.props.args.grid_options)) {
+            this.preSelectAllRows = this.props.args.grid_options["preSelectAllRows"];
+            delete this.props.args.grid_options["preSelectAllRows"];
+        }
```
Comment (jwood983) [inline streamlit_aggrid_redux/frontend/src/AgGrid.tsx:192]: I was getting JS warnings about invalid grid_options parameters, so I check and remove these

File: streamlit_aggrid_redux/frontend/src/AgGrid.tsx [hunk 3]
```diff
@@ -304,33 +304,21 @@ class AgGrid<S = {}> extends React.Component<ComponentProps, S> {
                 break
         }
         
-        let selected: any = {}
-        this.api.forEachDetailGridInfo((d: DetailGridInfo) => {
-            selected[d.id] = []
```
Comment (jwood983) [inline streamlit_aggrid_redux/frontend/src/AgGrid.tsx:309]: This code block returned nothing, so I removed it

File: streamlit_aggrid_redux/grid_builder.py [hunk 4]
```diff
@@ -102,6 +102,22 @@ def _process_css(custom_css: Union[Dict, str]) -> Dict:
         raise GridBuilderError(
             f"Custom CSS is neither a dict nor a string by {type(custom_css)}"
         )
+    
+def _process_update_on(updates: List[str], options: Dict) -> List[str]:
+    """ Ensure that updates include columnVisible and if we have checkboxes visible. """
```
Comment (jwood983) [inline streamlit_aggrid_redux/grid_builder.py:107]: This function is what generates the fix for #13: it pushes the `selectionChanged` listener when `checkbox` is requested
